name: timesheet
description: Timesheet mobile application.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <5.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  intl: ^0.20.2
  font_awesome_flutter: 10.6.0
  flutter_hooks: ^0.20.4
  flutter_dotenv: ^5.1.0
  email_validator: ^2.1.17
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  jwt_decoder: ^2.0.1
  go_router: ^12.1.3
  fl_chart: ^0.65.0
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  graphql_codegen: ^0.13.0
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
